#opt
train_epoch: 50           # number of epochs
warmup_epoch: 0           # number of warm-up epochs
wd: 0.00005                # weight decay
lr: 0.05                   # learning rate
min_lr: 0

#dset
dataset: BRACS
n_class: 3                            # number of classes
data_dir: './Feature/BRACSFeature/patch_feats_pretrain_medical_ssl.h5'         # directory of dataset
n_worker: 8                          # number of workers
pin_memory: False                     # use pin memory in dataloader
n_shot: -1

# Contrastive Loss Parameters
B: 16                          # batch size
use_contrastive_loss: True     # whether to use contrastive loss
temperature: 0.3               # temperature for contrastive loss
alpha: 0.7                     # weight for contrastive loss

# pretrained
backbone: 'ViT-S/16'
pretrain: 'medical_ssl'
D_feat: 384
D_inner: 128
