
# Contrastive Loss Parameters
B: 16                          # batch size
use_contrastive_loss: True     # whether to use contrastive loss
temperature: 0.3               # temperature for contrastive loss
alpha: 0.5                     # weight for contrastive loss


#opt
train_epoch: 30           # number of epochs
warmup_epoch: 1           # number of warm-up epochs
wd: 0.00005               # weight decay
lr: 0.001
min_lr: 0
#dset
dataset: CAMELYON17
n_class: 4                            # number of classes
data_dir: './Feature/camelyon17Feature/patch_feats_pretrain_medical_ssl.h5'       # directory of dataset
n_worker: 8                          # number of workers
pin_memory: False                     # use pin memory in dataloader
n_shot: -1

# pretrained
backbone: 'ViT-S/16'
pretrain: 'medical_ssl'
D_feat: 384
D_inner: 128